title: How to start a Podcast 
description: Technical Communication Final project 
theme: just-the-docs

url: https://karolinaga.github.io/How_to_Start_a_Podcast/


assets:
  sources:
    - assets

aux_links:
    - https://karolinaga.github.io/How_to_Start_a_Podcast/

 # Enable opening external links in a new tab
  opens_in_new_tab: true

favicon_ico: "/assets/images/HTSPLogo.jpg"

logo: "/assets/images/HTSPLogo.jpg"



# Footer content
# appears at the bottom of every page's main content

footer_content: "Copyright &copy; 2024 Karolina Gawrys. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"

